# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WD_Login.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WD_LogIn(object):
    def setupUi(self, WD_LogIn):
        WD_LogIn.setObjectName("WD_LogIn")
        WD_LogIn.resize(443, 340)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WD_LogIn)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WD_LogIn)
        self.tabWidget.setToolTip("")
        self.tabWidget.setStatusTip("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.formLayout = QtWidgets.QFormLayout(self.tabWidgetPage1)
        self.formLayout.setContentsMargins(9, 9, 9, 9)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.tabWidgetPage1)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.WD_LogIn_Usr = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.WD_LogIn_Usr.setText("")
        self.WD_LogIn_Usr.setObjectName("WD_LogIn_Usr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.WD_LogIn_Usr)
        self.Label_2 = QtWidgets.QLabel(self.tabWidgetPage1)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.WD_LogIn_Pwd = QtWidgets.QLineEdit(self.tabWidgetPage1)
        self.WD_LogIn_Pwd.setObjectName("WD_LogIn_Pwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.WD_LogIn_Pwd)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tabWidgetPage2)
        self.formLayout_2.setContentsMargins(9, 9, 9, 9)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.label = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.WD_LogIn_MaxConnnectTryTime = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_LogIn_MaxConnnectTryTime.setObjectName("WD_LogIn_MaxConnnectTryTime")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.WD_LogIn_MaxConnnectTryTime)
        self.WD_LogIn_WaitTimeAfterTryConnect = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_LogIn_WaitTimeAfterTryConnect.setObjectName("WD_LogIn_WaitTimeAfterTryConnect")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.WD_LogIn_WaitTimeAfterTryConnect)
        self.label_3 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WD_Login_ExchangeServerHost = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_Login_ExchangeServerHost.setObjectName("WD_Login_ExchangeServerHost")
        self.horizontalLayout.addWidget(self.WD_Login_ExchangeServerHost)
        self.WD_Login_ExchangeServerPort = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_Login_ExchangeServerPort.setObjectName("WD_Login_ExchangeServerPort")
        self.horizontalLayout.addWidget(self.WD_Login_ExchangeServerPort)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WD_Mkt_MktServerHost = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_Mkt_MktServerHost.setObjectName("WD_Mkt_MktServerHost")
        self.horizontalLayout_2.addWidget(self.WD_Mkt_MktServerHost)
        self.WD_Mkt_MktServerPort = QtWidgets.QLineEdit(self.tabWidgetPage2)
        self.WD_Mkt_MktServerPort.setObjectName("WD_Mkt_MktServerPort")
        self.horizontalLayout_2.addWidget(self.WD_Mkt_MktServerPort)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tabWidgetPage3)
        self.formLayout_3.setContentsMargins(9, 9, 9, 9)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_4 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.WD_LogIn_CounterType = QtWidgets.QLineEdit(self.tabWidgetPage3)
        self.WD_LogIn_CounterType.setObjectName("WD_LogIn_CounterType")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.WD_LogIn_CounterType)
        self.Label_5 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.WD_Login_CommissionRate = QtWidgets.QLineEdit(self.tabWidgetPage3)
        self.WD_Login_CommissionRate.setObjectName("WD_Login_CommissionRate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.WD_Login_CommissionRate)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.BT_LogIn = QtWidgets.QPushButton(WD_LogIn)
        self.BT_LogIn.setObjectName("BT_LogIn")
        self.verticalLayout.addWidget(self.BT_LogIn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WD_LogIn)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WD_LogIn)

    def retranslateUi(self, WD_LogIn):
        _translate = QtCore.QCoreApplication.translate
        WD_LogIn.setWindowTitle(_translate("WD_LogIn", "登录"))
        self.Label.setText(_translate("WD_LogIn", "用户："))
        self.Label_2.setText(_translate("WD_LogIn", "密码："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("WD_LogIn", "用户登录"))
        self.Label_3.setText(_translate("WD_LogIn", "交易服务地址："))
        self.label.setText(_translate("WD_LogIn", "行情服务地址："))
        self.label_2.setText(_translate("WD_LogIn", "最大重连次数："))
        self.label_3.setText(_translate("WD_LogIn", "等待重连间隔："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("WD_LogIn", "连接设置"))
        self.Label_4.setText(_translate("WD_LogIn", "柜台类型："))
        self.Label_5.setText(_translate("WD_LogIn", "佣金费率："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("WD_LogIn", "其他设置"))
        self.BT_LogIn.setText(_translate("WD_LogIn", "登录"))

